# docker-compose.yml
version: "3.8"
services:
   frontend:
     build:
       context: .
       dockerfile: Dockerfile
     volumes:
       - ./:/Users/swaggy/Desktop/login-google-auth0
       - /Users/swaggy/Desktop/login-google-auth0/node_modules
     ports:
       - 3000:3000
     environment:
       - CHOKIDAR_USEPOLLING=true